### ISSUE TITLE
Question: does a callback return a value?

### ISSUE THREAD

**Issue by gphg** [paltze/scenery#2]
I checked, it doesn't return any value, __yet__.

There one or two callbacks return a value, for example `love.quit`. It would be nice if it could do something like this:
```lua
function love.quit()
    return scenery:quit() -- if "false", abort quit
end
```
At the moment, I defined a global variable to set whatever the game is allowed to quit or not.

**Comment by paltze** [comment]
I actually didn't know some functions need to return values. Fixed.
