### ISSUE TITLE
Suggestion: using love.handlers instead harcoded loveCallbacks.

### ISSUE THREAD

**Issue by gphg** [paltze/scenery#3]
`love.handlers` is a table where you can define functions to handle user-defined events and executed under default `love.run`. It is documented here:
* https://love2d.org/wiki/love.run
* https://love2d.org/wiki/love.event

The table is \*kinda\* similar to `loveCallbacks`, but it excludes callbacks that isn't supposed to run under `love.run`. Here the list of excluded callbacks:
* errhand
* errorhandler
* load
* run
* update

**Comment by paltze** [comment]
Thanks, I will look into it

**Comment by paltze** [comment]
Sorry, I was a bit busy lately. 

> `love.handlers` is a table where you can define functions to handle user-defined events and executed under default `love.run`

Could you please elaborate. I tried going like:
```lua
love.handlers.draw = function ()
    print('Worked!')
end
```
But didn't get any output.

**Comment by gphg** [comment]
I made forked repo and it makes use the handler, please check it out. It doesn't have much change. I make use `love.handlers` table and loop over it, but instead index it's key.

Addendum:
Noticable changes at https://github.com/gphg/scenery/commit/c77bb2d04697b27370ca27a8e6abfb15a335811b
It was done on last month and I'm kinda *lost in touch*, I'll recheck it again. I'm sure it would works and the way to make use it is no difference than normal way.

**Comment by gphg** [comment]
Reference on `love.handlers`, it's defined on this file: https://github.com/love2d/love/blob/11.4/src/modules/love/callbacks.lua#L30

Looks like available on branch `12.0-development` too.
